$axure.loadCurrentPage({
  "url":"add_note.html",
  "generationDate":new Date(1396130837367.16),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6b31d1f60b1f4a1b9d35b6d351025e0a",
    "type":"Axure:Page",
    "name":"Add Note",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d5dc6295c3ea433790932ccc6bd16d2e",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":50},
            "size":{
              "width":400,
              "height":120}},
          "adaptiveStyles":{
}},
{
          "id":"db267018ec33430e9edb20f866183278",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":180},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "d5dc6295c3ea433790932ccc6bd16d2e":{
      "scriptId":"u0"},
    "db267018ec33430e9edb20f866183278":{
      "scriptId":"u1"}}});