$axure.loadCurrentPage({
  "url":"notes.html",
  "generationDate":new Date(1396130837433.49),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6789ab860ac14b60b9ccefa9423dc166",
    "type":"Axure:Page",
    "name":"Notes",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"center",
      "imageVerticalAlignment":"center",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"be5425a40f65478f9d6cecdd9f0e68c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":60},
            "size":{
              "width":480,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f5c506b5782480e949e3235783c68b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":60},
                "size":{
                  "width":480,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"999b3971c60b4039bb540c8efe6ce842",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":30},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23405314c0864b538de0655d00ce626b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":30},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/notes/u2.png"}},
{
          "id":"6a0e949343b24e19b777f90b4faf9362",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":44,
              "y":33},
            "size":{
              "width":66,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13f56d0e8fba4db08b4a2f5ec084a66a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":33},
                "size":{
                  "width":66,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f7c170fe1554059a516f1732465dd52",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial-ItalicMT', 'Arial Italic', 'Arial'",
            "fontSize":"11px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":350,
              "y":34},
            "size":{
              "width":97,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67deb448bfb04bdab38eee65d1c7ad0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial-ItalicMT', 'Arial Italic', 'Arial'",
                "fontSize":"11px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":34},
                "size":{
                  "width":97,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ca7a7162d3f4f93a01de90d92d79e38",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":100},
            "size":{
              "width":427,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/notes/u8_line.png"}},
{
          "id":"5769e795dac44f439ee8604973713347",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":150},
            "size":{
              "width":480,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10e14649b22a4f0b95778d9b39225802",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":150},
                "size":{
                  "width":480,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85d59047c1cf41cfa7f8bbe4418cdca7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":120},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e223334a4a742fb9b8ab32944bebb54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":120},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/notes/u2.png"}},
{
          "id":"4cc8eab404dc4d0785a8bd1c958921e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":44,
              "y":123},
            "size":{
              "width":66,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e07648ceae14ebda233db07aebc1e5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":123},
                "size":{
                  "width":66,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"accc89a8511d4facb53e9b39a802d87d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial-ItalicMT', 'Arial Italic', 'Arial'",
            "fontSize":"11px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":350,
              "y":124},
            "size":{
              "width":97,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64d72dc889c84de9a05929087a4732b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial-ItalicMT', 'Arial Italic', 'Arial'",
                "fontSize":"11px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":124},
                "size":{
                  "width":97,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8da6db162f24bf499561addf0b31d8a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":190},
            "size":{
              "width":427,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/notes/u8_line.png"}},
{
          "id":"a8c903dc626f43478fca10b5b6df8e08",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":239},
            "size":{
              "width":480,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd61a196ef714976a31795d3f8832053",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":239},
                "size":{
                  "width":480,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f1334f61c6e4b01a3ab153b206b8059",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":209},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a2a1f5b785f41c08da5c95a75f1cdd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":209},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/notes/u2.png"}},
{
          "id":"4b8fe67f47464605b580b5095abc94f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":44,
              "y":212},
            "size":{
              "width":66,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95a3c92a9efb4d13978c1a3261f0ae4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":212},
                "size":{
                  "width":66,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f1d38e593714e76a3bd7da1cc5c5fa2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial-ItalicMT', 'Arial Italic', 'Arial'",
            "fontSize":"11px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":350,
              "y":213},
            "size":{
              "width":97,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c555419ebbe347eaa3f26b8582a2fa5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial-ItalicMT', 'Arial Italic', 'Arial'",
                "fontSize":"11px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":213},
                "size":{
                  "width":97,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"851c60c513924c39ad365d869d83e49f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":279},
            "size":{
              "width":427,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/notes/u8_line.png"}},
{
          "id":"17c0d38c494841b5ba4abf5589fa9c9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":329},
            "size":{
              "width":480,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"469281ea5fbf4fd6affdcbca86d52a91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":329},
                "size":{
                  "width":480,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66ba67a6936b45f0a9042debcb9d405e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":299},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b04dc3c44f424fdd8bf371641cb8a5a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":299},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/notes/u2.png"}},
{
          "id":"9ceee4c844a940a19dffb23b0e4a4560",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":44,
              "y":302},
            "size":{
              "width":66,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba66bd9756f24738815f967faeaabede",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":302},
                "size":{
                  "width":66,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4858103e937b42e69aa089e77eeacb5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial-ItalicMT', 'Arial Italic', 'Arial'",
            "fontSize":"11px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":350,
              "y":303},
            "size":{
              "width":97,
              "height":12}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a77036fb6324615ba642833805fa107",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial-ItalicMT', 'Arial Italic', 'Arial'",
                "fontSize":"11px",
                "fontStyle":"italic",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":303},
                "size":{
                  "width":97,
                  "height":12}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da145f676f84444fa8831bd0057356c7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":369},
            "size":{
              "width":427,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/notes/u8_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "be5425a40f65478f9d6cecdd9f0e68c4":{
      "scriptId":"u0"},
    "5f5c506b5782480e949e3235783c68b8":{
      "scriptId":"u1"},
    "999b3971c60b4039bb540c8efe6ce842":{
      "scriptId":"u2"},
    "23405314c0864b538de0655d00ce626b":{
      "scriptId":"u3"},
    "6a0e949343b24e19b777f90b4faf9362":{
      "scriptId":"u4"},
    "13f56d0e8fba4db08b4a2f5ec084a66a":{
      "scriptId":"u5"},
    "3f7c170fe1554059a516f1732465dd52":{
      "scriptId":"u6"},
    "67deb448bfb04bdab38eee65d1c7ad0c":{
      "scriptId":"u7"},
    "3ca7a7162d3f4f93a01de90d92d79e38":{
      "scriptId":"u8"},
    "5769e795dac44f439ee8604973713347":{
      "scriptId":"u9"},
    "10e14649b22a4f0b95778d9b39225802":{
      "scriptId":"u10"},
    "85d59047c1cf41cfa7f8bbe4418cdca7":{
      "scriptId":"u11"},
    "8e223334a4a742fb9b8ab32944bebb54":{
      "scriptId":"u12"},
    "4cc8eab404dc4d0785a8bd1c958921e0":{
      "scriptId":"u13"},
    "8e07648ceae14ebda233db07aebc1e5f":{
      "scriptId":"u14"},
    "accc89a8511d4facb53e9b39a802d87d":{
      "scriptId":"u15"},
    "64d72dc889c84de9a05929087a4732b9":{
      "scriptId":"u16"},
    "f8da6db162f24bf499561addf0b31d8a":{
      "scriptId":"u17"},
    "a8c903dc626f43478fca10b5b6df8e08":{
      "scriptId":"u18"},
    "bd61a196ef714976a31795d3f8832053":{
      "scriptId":"u19"},
    "2f1334f61c6e4b01a3ab153b206b8059":{
      "scriptId":"u20"},
    "5a2a1f5b785f41c08da5c95a75f1cdd9":{
      "scriptId":"u21"},
    "4b8fe67f47464605b580b5095abc94f2":{
      "scriptId":"u22"},
    "95a3c92a9efb4d13978c1a3261f0ae4b":{
      "scriptId":"u23"},
    "4f1d38e593714e76a3bd7da1cc5c5fa2":{
      "scriptId":"u24"},
    "c555419ebbe347eaa3f26b8582a2fa5c":{
      "scriptId":"u25"},
    "851c60c513924c39ad365d869d83e49f":{
      "scriptId":"u26"},
    "17c0d38c494841b5ba4abf5589fa9c9b":{
      "scriptId":"u27"},
    "469281ea5fbf4fd6affdcbca86d52a91":{
      "scriptId":"u28"},
    "66ba67a6936b45f0a9042debcb9d405e":{
      "scriptId":"u29"},
    "b04dc3c44f424fdd8bf371641cb8a5a9":{
      "scriptId":"u30"},
    "9ceee4c844a940a19dffb23b0e4a4560":{
      "scriptId":"u31"},
    "ba66bd9756f24738815f967faeaabede":{
      "scriptId":"u32"},
    "4858103e937b42e69aa089e77eeacb5a":{
      "scriptId":"u33"},
    "0a77036fb6324615ba642833805fa107":{
      "scriptId":"u34"},
    "da145f676f84444fa8831bd0057356c7":{
      "scriptId":"u35"}}});